/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Italk2learn */

#ifndef _Included_iT2L
#define _Included_iT2L
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Italk2learn
 * Method:    hello
 * Signature: ()Tludmetal
 */
JNIEXPORT jstring JNICALL Java_Italk2learn_hello
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
